apiVersion: v1
kind: Service
metadata:
  name: {{ include "bank.fullname" . }}-bankapp-service
  labels:
  {{- include "bank.labels" . | nindent 4 }}
spec:
  type: {{ .Values.bankappService.type }}
  selector:
    app: bankapp
    version: blue
    {{- include "bank.selectorLabels" . | nindent 4 }}
  ports:
  {{- .Values.bankappService.ports | toYaml | nindent 2 }}
